Now using SSPORT, SSOPTIONS, and SSSTATE variablse

diff --git a/ssq b/ssq
--- a/ssq
+++ b/ssq
@@ -1,12 +1,13 @@
-unset ss
-set -x
-set -e
+# unset ss
+# set -x # enable for debugging
+set -e # exit on error
 . ss.fun
-ss 22 2>&1 | less
-
-ss 22 state established 2>&1 | less
-
-ss 53 -ulpne  2>&1 | less
-
-ss 53 -ul state all 2>&1 | less
+ss ssh 2>&1 | more
+echo
+ss 22 state established 2>&1 | more
+echo
+ss domain -ulpne  2>&1 | more
+echo
+ss 53 -ul state all 2>&1 | more
+echo
 
